// GENERATED by scripts/sync-consent-copy.mjs from lib/consent/catalog.ts in the
// app repo. Do not edit here — edit the app file and run `npm run consent:sync`.

// The consent catalogue: which purposes we ask about, which partners process
// data, and what each partner is allowed to do. The purpose names and the
// "special purposes / features" are the IAB TCF v2.2 standard set, so the
// wording matches what people see in every other app (Cal AI shows the same
// list through Didomi). Copy lives in i18n/locales/<lang>/consent.json under
// `purposes.<id>`, `features.<id>` and `partners.<id>`.
//
// Copied into cal-clark-landing/src/lib/consent/ by `npm run consent:sync` —
// the landing is a separate git repo and cannot import through this app's
// tsconfig paths. Edit here, then run the sync. The server keeps its own
// slice (ids + required flags) in server/src/consent/catalog.ts by hand.

export const CONSENT_VERSION = 1;

/** In display order. */
export const PURPOSE_IDS = [
  "store_access",
  "create_ad_profiles",
  "use_ad_profiles",
  "develop_improve",
  "understand_audiences",
  "measure_ad_performance",
  "limited_data_ads",
  "functional",
  "create_content_profiles",
  "measure_content",
  "use_content_profiles",
  "social",
  "required",
] as const;
export type PurposeId = (typeof PURPOSE_IDS)[number];

/**
 * - consent: off until the person switches it on.
 * - legitimate_interest: on by default, the person may object (switch off).
 * - required: always on, cannot be switched off (the app does not work
 *   without it).
 */
export type LegalBasis = "consent" | "legitimate_interest" | "required";

export const PURPOSE_BASIS: Record<PurposeId, LegalBasis> = {
  store_access: "consent",
  create_ad_profiles: "consent",
  use_ad_profiles: "consent",
  develop_improve: "legitimate_interest",
  understand_audiences: "legitimate_interest",
  measure_ad_performance: "legitimate_interest",
  limited_data_ads: "legitimate_interest",
  functional: "legitimate_interest",
  create_content_profiles: "consent",
  measure_content: "consent",
  use_content_profiles: "consent",
  social: "consent",
  required: "required",
};

/** Explained inline under the purposes; no toggle (IAB special purposes / features). */
export const FEATURE_IDS = [
  "deliver_content",
  "security",
  "identify_devices",
  "link_devices",
  "match_data",
  "save_choices",
] as const;
export type FeatureId = (typeof FEATURE_IDS)[number];

export const PARTNER_IDS = [
  "appsflyer",
  "clerk",
  "google_ads",
  "posthog",
  "revenuecat",
  "resend",
  "sentry",
  "vercel",
] as const;
export type PartnerId = (typeof PARTNER_IDS)[number];

export type Surface = "app" | "web";

export type Partner = {
  id: PartnerId;
  /** Display name, shown as-is in every language. */
  name: string;
  /** Where the partner actually runs. Filtered out of the list elsewhere. */
  surfaces: readonly Surface[];
  /** Always on: the product does not work without it. No toggle. */
  required: boolean;
  purposes: readonly PurposeId[];
  /**
   * The purposes that must ALL be on before this partner's SDK may start.
   * The rest of `purposes` are what it does once running. Empty for required
   * partners.
   */
  gate: readonly PurposeId[];
  features: readonly FeatureId[];
  privacyUrl: string;
};

export const PARTNERS: readonly Partner[] = [
  {
    id: "appsflyer",
    name: "AppsFlyer",
    surfaces: ["app", "web"],
    required: false,
    purposes: [
      "store_access",
      "understand_audiences",
      "measure_ad_performance",
      "limited_data_ads",
    ],
    gate: ["store_access"],
    features: [
      "deliver_content",
      "security",
      "identify_devices",
      "link_devices",
      "save_choices",
    ],
    privacyUrl: "https://www.appsflyer.com/legal/services-privacy-policy/",
  },
  {
    id: "clerk",
    name: "Clerk",
    surfaces: ["app"],
    required: true,
    purposes: ["required", "functional"],
    gate: [],
    features: ["security", "save_choices"],
    privacyUrl: "https://clerk.com/legal/privacy",
  },
  {
    id: "google_ads",
    name: "Google Advertising Products",
    surfaces: ["app", "web"],
    required: false,
    purposes: [
      "store_access",
      "create_ad_profiles",
      "use_ad_profiles",
      "measure_ad_performance",
      "limited_data_ads",
    ],
    gate: ["store_access"],
    features: ["deliver_content", "security", "match_data", "link_devices"],
    privacyUrl: "https://business.safety.google/privacy/",
  },
  {
    id: "posthog",
    name: "PostHog",
    surfaces: ["app"],
    required: false,
    purposes: ["develop_improve", "understand_audiences", "measure_content"],
    gate: ["develop_improve"],
    features: ["security", "save_choices"],
    privacyUrl: "https://posthog.com/privacy",
  },
  {
    id: "revenuecat",
    name: "RevenueCat",
    surfaces: ["app"],
    required: true,
    purposes: ["required"],
    gate: [],
    features: ["security"],
    privacyUrl: "https://www.revenuecat.com/privacy",
  },
  {
    id: "resend",
    name: "Resend",
    surfaces: ["app", "web"],
    required: true,
    purposes: ["required", "functional"],
    gate: [],
    features: ["security"],
    privacyUrl: "https://resend.com/legal/privacy-policy",
  },
  {
    id: "sentry",
    name: "Sentry",
    surfaces: ["app"],
    required: true,
    purposes: ["required", "functional"],
    gate: [],
    features: ["security"],
    privacyUrl: "https://sentry.io/privacy/",
  },
  {
    id: "vercel",
    name: "Vercel",
    surfaces: ["web"],
    required: true,
    purposes: ["required"],
    gate: [],
    features: ["security", "deliver_content"],
    privacyUrl: "https://vercel.com/legal/privacy-policy",
  },
];

export type PurposeChoices = Record<PurposeId, boolean>;
export type PartnerChoices = Record<PartnerId, boolean>;

export type ConsentChoices = {
  purposes: PurposeChoices;
  partners: PartnerChoices;
};

export function partnersFor(surface: Surface): Partner[] {
  return PARTNERS.filter((p) => p.surfaces.includes(surface));
}

/** What the screen shows before anyone touches a switch. */
export function defaultChoices(): ConsentChoices {
  const purposes = {} as PurposeChoices;
  for (const id of PURPOSE_IDS) {
    purposes[id] = PURPOSE_BASIS[id] !== "consent";
  }
  const partners = {} as PartnerChoices;
  for (const p of PARTNERS) {
    // A partner that runs on legitimate interest (every gate purpose is
    // LI/required, e.g. PostHog) starts on, like its purposes. A partner that
    // needs consent to start at all (AppsFlyer, Google Ads) starts off - the
    // same picture as the Didomi partner list Cal AI shows.
    partners[p.id] =
      p.required || p.gate.every((id) => PURPOSE_BASIS[id] !== "consent");
  }
  return { purposes, partners };
}

export function acceptAllChoices(): ConsentChoices {
  const purposes = {} as PurposeChoices;
  for (const id of PURPOSE_IDS) purposes[id] = true;
  const partners = {} as PartnerChoices;
  for (const p of PARTNERS) partners[p.id] = true;
  return { purposes, partners };
}

export function rejectAllChoices(): ConsentChoices {
  const purposes = {} as PurposeChoices;
  for (const id of PURPOSE_IDS) purposes[id] = PURPOSE_BASIS[id] === "required";
  const partners = {} as PartnerChoices;
  for (const p of PARTNERS) partners[p.id] = p.required;
  return { purposes, partners };
}

/**
 * Required purposes and partners are always on, whatever a stale client or a
 * hand-edited request says. Unknown keys are dropped.
 */
export function normalizeChoices(input: {
  purposes?: Partial<Record<string, boolean>>;
  partners?: Partial<Record<string, boolean>>;
}): ConsentChoices {
  const base = rejectAllChoices();
  for (const id of PURPOSE_IDS) {
    if (PURPOSE_BASIS[id] === "required") continue;
    const value = input.purposes?.[id];
    if (typeof value === "boolean") base.purposes[id] = value;
  }
  for (const p of PARTNERS) {
    if (p.required) continue;
    const value = input.partners?.[p.id];
    if (typeof value === "boolean") base.partners[p.id] = value;
  }
  return base;
}

/** A partner's SDK may start only when it is on AND every purpose in its `gate` is on. */
export function partnerAllowed(choices: ConsentChoices, id: PartnerId): boolean {
  const partner = PARTNERS.find((p) => p.id === id);
  if (!partner) return false;
  if (partner.required) return true;
  if (!choices.partners[id]) return false;
  return partner.gate.every((purpose) => choices.purposes[purpose]);
}

/**
 * Whether to show Apple's App Tracking Transparency prompt: only when the
 * person allowed device storage/access and an attribution partner may run.
 */
export function wantsAppleTracking(choices: ConsentChoices): boolean {
  return (
    choices.purposes.store_access &&
    (partnerAllowed(choices, "appsflyer") || partnerAllowed(choices, "google_ads"))
  );
}
